/**
 * Base verbiages, spread first in PaymentChild.tsx:
 *   { ...DEFAULT_VERBIAGES, ...(pacsFormVerbiagesInput || {}) }
 * PaymentParent.tsx's PARENT_VERBIAGES then overrides most of these at
 * runtime via the pacsFormVerbiages prop. This file supplies the two keys
 * PARENT_VERBIAGES does NOT define (PaymentDetails, BeneficiaryDetails —
 * the two mega-section headers) plus a full base set so PaymentChild.tsx
 * still renders sensibly even if used without PaymentParent's overrides.
 */
export const DEFAULT_VERBIAGES: Record<string, string> = {
  PaymentDetails: 'Payment Details',
  BeneficiaryDetails: 'Beneficiary Details',
  // ADDED: title for the new dynamic "Additional Fields" section — distinct
  // from the existing AdditionalDetails key (charges/remittance section).
  AdditionalFields: 'Additional Fields',

  DebtorInfo: 'Debtor Information',
  ValueDate: 'Value Date',
  ValueDateIsRequired: 'Value Date is required',
  DebtorName: 'Debtor Name',
  DebtorNameIsRequired: 'Debtor Name is required',
  DebtorAccountNumber: 'Debtor Account Number',
  DebtorAccountNumberIsRequired: 'Debtor Account Number is required',
  DebtorAgentBIC: 'Debtor Agent BIC',
  DebtorAgentBicIsRequired: 'Debtor Agent BIC is required',
  ChargeInformation: 'Charge Information',
  ChargesAmount: 'Charges Amount',
  ChargesAgentBic: 'Charges Agent BIC',
  DebtorAddress: 'Debtor Address',
  DebtorStreet: 'Debtor Street',
  DebtorBuildingNumber: 'Debtor Building Number',
  DebtorPostalCode: 'Debtor Postal Code',
  DebtorTownOrCityName: 'Debtor Town / City Name',
  DebtorState: 'Debtor State',
  DebtorCountry: 'Debtor Country',
  DebtorSortCode: 'Debtor Sort Code',
  TransactionDetails: 'Transaction Details',
  TransactionAmount: 'Transaction Amount',
  TransactionAmountIsRequired: 'Transaction Amount is required (min 0)',
  ValidatingHardcapLimit: 'Validating hardcap limit...',
  Currency: 'Currency',
  CurrencyIsRequired: 'Currency is required',
  PaymentType: 'Payment Type (CBT, BKT, DFT)',
  PaymentTypeIsRequired: 'Payment Type is required',
  RemittanceInformation: 'Remittance Information',
  CreditorInformation: 'Creditor Information',
  CreditorName: 'Creditor Name',
  CreditorNameIsRequired: 'Creditor Name is required',
  CreditorAccountNumber: 'Creditor Account Number',
  CreditorAccountNumberIsRequired: 'Creditor Account Number is required',
  CreditorAgentBIC: 'Creditor Agent BIC',
  Required: 'Required',
  CreditorAgentBankName: 'Creditor Agent Bank Name',
  creditorAgentPostalAddress: 'Creditor Agent Account Number',
  CreditorAddress: 'Creditor Address',
  CreditorStreet: 'Creditor Street',
  CreditorBuildingNumber: 'Creditor Building Number',
  CreditorPostalCode: 'Creditor Postal Code',
  CreditorTownOrCityName: 'Creditor Town / City Name',
  CreditorState: 'Creditor State',
  CreditorCountry: 'Creditor Country',
  CreditorSortCode: 'Creditor Sort Code',
  SecondIntermediaryBank: '2nd Intermediary Bank',
  SecondIntermediaryBankSWIFTCode: '2nd Intermediary Bank SWIFT Code',
  SecondIntermediaryBankRoutingCode: '2nd Intermediary Bank Routing Code',
  SecondIntermediaryBankName: '2nd Intermediary Bank Name',
  SecondIntermediaryBankCountryCode: '2nd Intermediary Bank Country Code',
  SecondIntermediaryAccountNumber: '2nd Intermediary Account Number',
  FirstIntermediaryBank: '1st Intermediary Bank',
  FirstIntermediaryBankSWIFTCode: '1st Intermediary Bank SWIFT Code',
  FirstIntermediaryBankRoutingCode: '1st Intermediary Bank Routing Code',
  FirstIntermediaryBankName: '1st Intermediary Bank Name',
  FirstIntermediaryBankCountryCode: '1st Intermediary Bank Country Code',
  FirstIntermediaryAccountNumber: '1st Intermediary Account Number',
  AdditionalDetails: 'Additional Details',
  ChargeDetails: 'Charge Details',
  PaymentInformation: 'Payment Information',
  DebtorAddressDetails: 'Debtor Address Details',
  IntermediaryBankDetails: 'Intermediary Bank Details',
  CreditorAddressDetails: 'Creditor Address Details',
  DebtorAddressLine1: 'Debtor Address Line 1',
  DebtorAddressLine2: 'Debtor Address Line 2',
  DebtorCountrySubDivisionLabel: 'Debtor Country Sub Division',
  CreditorAddressLine1: 'Creditor Address Line 1',
  CreditorAddressLine2: 'Creditor Address Line 2',
  CreditorCountrySubDivisionLabel: 'Creditor Country Sub Division',
  SubmitPayment: 'Submit Payment',
};
