// Ported from ss-payment-flow.component.ts DEFAULT_VERBIAGES static map.
// The child merges this with whatever pacsFormVerbiages the parent passes in:
//   pacsFormVerbiages = {...DEFAULT_VERBIAGES, ...(pacsFormVerbiagesInput || {})}
// The PARENT in this app supplies its OWN, mostly-overlapping-but-not-identical
// verbiages object (see PaymentParent's PARENT_VERBIAGES below) — both are kept
// distinct and merged the same way the Angular source does, rather than unified,
// per the "preserve exactly as photographed" instruction.

export const DEFAULT_VERBIAGES: Record<string, string> = {
  PaymentDetails: 'Payment Details',
  DebtorInformation: 'Debtor Information',
  BeneficiaryDetails: 'Beneficiary Details',
  AdditionalInformation: 'Additional Information',
  PaymentInformation: 'Payment Information',
  ValueDate: 'Value Date',
  ValueDateIsRequired: 'Value Date is required',
  Currency: 'Currency',
  CurrencyIsRequired: 'Currency is required',
  TransactionAmount: 'Transaction Amount',
  TransactionAmountIsRequired: 'Transaction Amount is required (min 0)',
  ValidatingHardcapLimit: 'Validating hardcap limit...',
  DebtorInfo: 'Debtor Information',
  DebtorName: 'Debtor Name',
  DebtorNameIsRequired: 'Debtor Name is required',
  DebtorAccountNumber: 'Debtor Account Number',
  DebtorAccountNumberIsRequired: 'Debtor Account Number is required',
  DebtorAgentBIC: 'Debtor Agent BIC',
  DebtorAgentBicIsRequired: 'Debtor Agent BIC is required',
  DebtorAddress: 'Debtor Address',
  DebtorAddressDetails: 'Debtor Address Details',
  DebtorAddressLine1: 'Debtor Address Line 1',
  DebtorAddressLine2: 'Debtor Address Line 2',
  DebtorStreet: 'Debtor Street',
  DebtorBuildingNumber: 'Debtor Building Number',
  DebtorPostalCode: 'Debtor Postal Code',
  DebtorTownOrCityName: 'Debtor Town / City Name',
  DebtorCountrySubDivisionLabel: 'Debtor Country Sub Division',
  DebtorState: 'Debtor State',
  DebtorCountry: 'Debtor Country',
  DebtorSortCode: 'Debtor Sort Code',
  IntermediaryBankDetails: 'Intermediary Bank Details',
  FirstIntermediaryBank: '1st Intermediary Bank',
  FirstIntermediaryBankSWIFTCode: '1st Intermediary Bank SWIFT Code',
  FirstIntermediaryBankRoutingCode: '1st Intermediary Bank Routing Code',
  FirstIntermediaryBankName: '1st Intermediary Bank Name',
  FirstIntermediaryBankCountryCode: '1st Intermediary Bank Country Code',
  FirstIntermediaryAccountNumber: '1st Intermediary Account Number',
  SecondIntermediaryBank: '2nd Intermediary Bank',
  SecondIntermediaryBankSWIFTCode: '2nd Intermediary Bank SWIFT Code',
  SecondIntermediaryBankRoutingCode: '2nd Intermediary Bank Routing Code',
  SecondIntermediaryBankName: '2nd Intermediary Bank Name',
  SecondIntermediaryBankCountryCode: '2nd Intermediary Bank Country Code',
  SecondIntermediaryAccountNumber: '2nd Intermediary Account Number',
  CreditorInformation: 'Creditor Information',
  CreditorAddressDetails: 'Creditor Address Details',
  CreditorName: 'Creditor Name',
  CreditorNameIsRequired: 'Creditor Name is required',
  CreditorAccountNumber: 'Creditor Account Number',
  CreditorAccountNumberIsRequired: 'Creditor Account Number is required',
  CreditorAgentBIC: 'Creditor Agent BIC',
  Required: 'Required',
  CreditorAgentBankName: 'Creditor Agent Bank Name',
  CreditorAddress: 'Creditor Address',
  CreditorAddressLine1: 'Creditor Address Line 1',
  CreditorAddressLine2: 'Creditor Address Line 2',
  CreditorStreet: 'Creditor Street',
  CreditorBuildingNumber: 'Creditor Building Number',
  CreditorPostalCode: 'Creditor Postal Code',
  CreditorTownOrCityName: 'Creditor Town / City Name',
  CreditorCountrySubDivisionLabel: 'Creditor Country Sub Division',
  CreditorState: 'Creditor State',
  CreditorCountry: 'Creditor Country',
  CreditorSortCode: 'Creditor Sort Code',
  AdditionalDetails: 'Additional Details',
  ChargeDetails: 'Charge Details',
  ChargesAmount: 'Charges Amount',
  ChargesAgentBic: 'Charges Agent BIC',
  PaymentType: 'Payment Type (CBT, BKT, DFT)',
  PaymentTypeIsRequired: 'Payment Type is required',
  RemittanceInformation: 'Remittance Information',
  SubmitPayment: 'Submit Payment',
};
