import { PaymentInstruction } from '../models';

const today = new Date();
const iso = (offsetDays = 0): string => {
  const d = new Date(today);
  d.setDate(d.getDate() + offsetDays);
  return d.toISOString();
};

export const MOCK_INSTRUCTIONS: PaymentInstruction[] = [
  {
    id: 'AR_20251124_5102',
    reference: 'AR_20251124_5102',
    status: 'admin-checker',
    clientInformation: {
      regionId: 'r-latam',
      countryId: 'c-arg',
      clientId: 'cl-msu',
      dealId: 'd-msu-1',
      contractValidationComplete: true,
    },
    instructionDetails: {
      requestType: 'Administrative Transactional',
      source: 'Email',
      senderEmail: 'msu-treasury@example.com',
      primaryAssigneeId: 'u-001',
      backupAssigneeId: null,
      category: 'Tax',
      description: 'Quarterly tax withholding payment for ARG bond program.',
      relatedInstructionIds: [],
      valueDate: iso(0),
      dueDate: iso(2),
      transactionDate: iso(-1),
    },
    additionalInformation: [],
    mppProcess: {
      citiDirectClientProfile: { reviewRequired: true },
      mppRequired: 'No',
      exception: 'Internal',
    },
    attachments: [
      {
        id: 'att-1',
        documentName: 'BRADL.docx',
        documentType: 'Keeper File Rev',
        region: 'LATAM',
        documentDated: null,
        oncUpload: true,
        uploadedBy: 'Swathi Iharra',
        uploadedOn: iso(-2),
      },
    ],
    signatureValidation: {
      validationSource: null,
      status: 'Pending',
      commentType: 'Signature Validation',
      sequenceNumber: 'PE_202508_2700',
    },
    callbacks: [],
    comments: [
      {
        id: 'cm-1',
        commentType: 'Admin Checker',
        comment: 'Approved',
        commentedBy: 'Ravi Kumar',
        commentedOn: iso(-1),
      },
    ],
    history: [
      { step: 'admin-maker', enteredAt: iso(-2), exitedAt: iso(-1), by: 'Swathi Iharra' },
      { step: 'admin-checker', enteredAt: iso(-1), by: 'Ravi Kumar' },
    ],
    createdBy: 'Swathi Iharra',
    createdOn: iso(-2),
    updatedOn: iso(-1),
  },
  {
    id: 'BR_20251119_5082',
    reference: 'BR_20251119_5082',
    status: 'signature-validation',
    clientInformation: {
      regionId: 'r-latam',
      countryId: 'c-bra',
      clientId: 'cl-camori',
      dealId: 'd-cam-1',
      contractValidationComplete: true,
    },
    instructionDetails: {
      requestType: 'Payment Instruction',
      source: 'CitiDirect',
      primaryAssigneeId: 'u-002',
      backupAssigneeId: 'u-001',
      category: 'Coupon',
      description: 'Coupon payment for Camorim Maritime Trust 2024-Q4.',
      relatedInstructionIds: [],
      valueDate: iso(1),
      dueDate: iso(3),
      transactionDate: iso(-3),
    },
    additionalInformation: [],
    mppProcess: {
      citiDirectClientProfile: { reviewRequired: false },
      mppRequired: 'Yes',
      exception: 'None',
    },
    attachments: [],
    signatureValidation: {
      validationSource: 'Bank Records',
      status: 'Pending',
      commentType: 'Signature Validation',
    },
    callbacks: [],
    comments: [],
    history: [
      { step: 'admin-maker', enteredAt: iso(-5), exitedAt: iso(-4), by: 'Cliver Scaria' },
      { step: 'admin-checker', enteredAt: iso(-4), exitedAt: iso(-3), by: 'Maria Gonzales' },
      { step: 'signature-validation', enteredAt: iso(-3), by: 'Venkata Rajeev Raju' },
    ],
    createdBy: 'Cliver Scaria',
    createdOn: iso(-5),
    updatedOn: iso(-3),
  },
  {
    id: 'MX_20251120_5099',
    reference: 'MX_20251120_5099',
    status: 'operations-callback',
    clientInformation: {
      regionId: 'r-latam',
      countryId: 'c-mex',
      clientId: 'cl-petromex',
      dealId: 'd-pmx-1',
      contractValidationComplete: true,
    },
    instructionDetails: {
      requestType: 'Payment Instruction',
      source: 'Email',
      senderEmail: 'pmx-ops@example.com',
      primaryAssigneeId: 'u-006',
      backupAssigneeId: null,
      category: 'Principal',
      description: 'Principal repayment — bridge facility tranche 2.',
      relatedInstructionIds: [],
      valueDate: iso(0),
      dueDate: iso(0),
      transactionDate: iso(-2),
    },
    additionalInformation: [],
    mppProcess: {
      citiDirectClientProfile: { reviewRequired: false },
      mppRequired: 'Yes',
      exception: 'None',
    },
    attachments: [],
    signatureValidation: { validationSource: 'Bank Records', status: 'Signature Approved', commentType: 'Signature Validation' },
    callbacks: [],
    comments: [],
    history: [],
    createdBy: 'Daniel Park',
    createdOn: iso(-7),
    updatedOn: iso(-1),
  },
  {
    id: 'US_20251121_5104',
    reference: 'US_20251121_5104',
    status: 'payment-completed',
    clientInformation: {
      regionId: 'r-nam',
      countryId: 'c-usa',
      clientId: 'cl-sigma',
      dealId: 'd-sig-1',
      contractValidationComplete: true,
    },
    instructionDetails: {
      requestType: 'Payment Instruction',
      source: 'CitiDirect',
      primaryAssigneeId: 'u-007',
      backupAssigneeId: null,
      category: 'Fee',
      description: 'Quarterly management fee.',
      relatedInstructionIds: [],
      valueDate: iso(-3),
      dueDate: iso(-1),
      transactionDate: iso(-4),
    },
    additionalInformation: [],
    mppProcess: {
      citiDirectClientProfile: { reviewRequired: false },
      mppRequired: 'No',
      exception: 'None',
    },
    attachments: [],
    signatureValidation: { validationSource: 'Bank Records', status: 'Signature Approved', commentType: 'Signature Validation' },
    callbacks: [],
    comments: [],
    history: [],
    createdBy: 'Priya Sharma',
    createdOn: iso(-10),
    updatedOn: iso(-1),
  },
  {
    id: 'GB_20251118_5070',
    reference: 'GB_20251118_5070',
    status: 'draft',
    clientInformation: {
      regionId: 'r-emea',
      countryId: 'c-gbr',
      clientId: 'cl-thames',
      dealId: 'd-tha-1',
      contractValidationComplete: false,
    },
    instructionDetails: {
      requestType: 'Account Maintenance',
      source: 'Manual',
      primaryAssigneeId: 'u-001',
      backupAssigneeId: null,
      category: 'Maintenance',
      description: '',
      relatedInstructionIds: [],
      valueDate: null,
      dueDate: null,
      transactionDate: null,
    },
    additionalInformation: [],
    mppProcess: {
      citiDirectClientProfile: { reviewRequired: false },
      mppRequired: null,
      exception: null,
    },
    attachments: [],
    signatureValidation: { validationSource: null, status: null, commentType: 'Signature Validation' },
    callbacks: [],
    comments: [],
    history: [],
    createdBy: 'Swathi Iharra',
    createdOn: iso(-1),
    updatedOn: iso(-1),
  },
];
